branch-defaults:
  main:
    environment: demo
deploy:
  artifact: target/app.jar
environment-defaults:
  demo:
    branch: null
    repository: null
global:
  application_name: demo-app
  default_ec2_keyname: null
  default_platform: Corretto 17 running on 64bit Amazon Linux 2023
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
